trigger:
- main  # Trigger the pipeline on pushes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent

steps:
- task: UseNode@2  # Install Node.js
  inputs:
    versionSpec: '14.x'  # Specify the version of Node.js
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli  # Install Angular CLI globally
    npm install  # Install project dependencies
  displayName: 'Install Angular CLI and npm packages'

- script: |
    ng build --prod --output-path=dist  # Build the Angular project
  displayName: 'Build Angular project'

- task: CopyFiles@2  # Copy the build output to the artifact staging directory
  inputs:
    SourceFolder: 'dist'  # Source folder containing the build output
    Contents: '**'  # Copy all files
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Target directory for the artifacts
  displayName: 'Copy files to artifact staging directory'

- task: PublishBuildArtifacts@1  # Publish the build artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path to the artifact staging directory
    ArtifactName: 'drop'  # Name of the artifact
  displayName: 'Publish build artifacts'

- task: AzureWebApp@1  # Deploy to Azure Web App
  inputs:
    azureSubscription: '<Your-Azure-Subscription>'  # Azure subscription name or ID
    appName: '<Your-Web-App-Name>'  # Name of the Azure Web App
    package: '$(Build.ArtifactStagingDirectory)/drop'  # Path to the artifacts to be deployed
  displayName: 'Deploy to Azure Web App'
